### ISSUE TITLE
UI | Logic | Past Contests leaderbord

### ISSUE THREAD

**Issue by n0macx** [CC2021-WBL/GOOD-BOI-Application#151]
![image](https://user-images.githubusercontent.com/66994199/150839931-f50d7608-bc0d-4339-82fa-c5725236908b.png)

- dynamniczne pobieranie wyników w zależności od aktywnej klasy
- sortowanie wyników od najwyższego do najniższego
- imitacja pobierania danych z bazy danych - na podstawie ID konkursu i klasy

**Comment by RobertS-ki** [comment]
Komponent LeaderboardList jest w stanie wyświetlić oba leaderboardy w zależności od ilości przekazanych propsów.
